version: "3.9"
services:
  express-todo-backend:
    build: ./express-todo-backend
    ports:
      - "4000:4000"
    volumes:
      - ./express-todo-backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - MONGODB_URI=
      - JWT_SECRET=
      - PORT=4000

